language: bash
services: docker

branches:
  except:
  - master

env:
  - VARIANT=php7.2/apache
  - VARIANT=php7.2/fpm
  - VARIANT=php7.2/fpm-alpine
  - VARIANT=php7.3/apache
  - VARIANT=php7.3/fpm
  - VARIANT=php7.3/fpm-alpine
  - VARIANT=php7.4/apache
  - VARIANT=php7.4/fpm
  - VARIANT=php7.4/fpm-alpine

install:
  - git clone https://github.com/docker-library/official-images.git ~/official-images

before_script:
  - env | sort
  - cd "$VARIANT"
  - slash='/'; tag="${VARIANT//$slash/-}"; image="tfirdaus/wp-docklines:$tag"

script:
  - travis_retry docker build -t "$image" .

after_script:
  - docker images
  - docker run "$image" /bin/sh -c "php --version; wp --version --allow-root; svn --version; git --version"